#!/bin/bash
#SBATCH --job-name=lncot_exp4
#SBATCH --partition=ecsstudents_l4
#SBATCH --account=ecsstudents
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=48G
#SBATCH --time=06:00:00
################################################################################
# Figure 4 Evaluation — iridis/lncot-exp4
#
# Reproduces Figure 4 of the paper: "Perplexity for different amounts of
# compute budgets chosen at inference."
#
# Usage:
#   cd ~/CoTFormer && bash iridis/lncot-exp4/job.sh
#
# PREREQUISITE: A fully trained adaptive LN-CoTFormer checkpoint.
#   The checkpoint directory must contain:
#     - ckpt.pt       (trained model weights — saved after training completes)
#     - summary.json  (experiment config — written by main.py on completion)
#
#   Train it with: bash iridis/adm-train/job.sh (may need 2-3 submissions)
#
# WHAT THIS DOES (2 phases):
#   Phase 1: Extract router weights from trained model
#     - Runs get_router_weights.py on a sample of the training data
#     - Outputs: <checkpoint_dir>/router_weights.npy
#
#   Phase 2: Evaluate at multiple compute budgets
#     - Runs get_ppl_per_mac.py which evaluates the model at:
#       (a) Router-derived thresholds (for "Router" curve in Figure 4)
#       (b) Fixed prefix depths (for "Fixed Depth" curve in Figure 4)
#     - Outputs: <checkpoint_dir>/eval_per_threshold.npy
#                <checkpoint_dir>/eval_per_layer.npy
#
# Both curves come from the SAME adaptive model checkpoint.
#
# After this job, use the .npy files to plot Figure 4 (Phase 5 plotting).
################################################################################

# ========================= CONFIGURATION ====================================

# Path to the trained adaptive model checkpoint directory.
# This is auto-generated by main.py based on model name and hyperparams.
# Find it under /scratch/ab3u21/exps/owt2/adaptive_cotformer_*/
#
# IMPORTANT: Set this to YOUR checkpoint path before submitting!
CHECKPOINT_DIR="/scratch/ab3u21/exps/owt2/adaptive_cotformer_mod_efficient_sigmoid_crw_lnmid_de_random_factor_single_final/adm_lr0.001_bs8x16_seqlen256"

# ========================= END CONFIGURATION ================================

# --- Self-submitting wrapper (runs on login node) ---
if [ -z "$SLURM_JOB_ID" ]; then
    PACKAGE_DIR="$(cd "$(dirname "$0")" && pwd)"
    REPO_DIR="$(cd "$PACKAGE_DIR/../.." && pwd)"
    source "$REPO_DIR/iridis/env.sh"

    # --- Pre-flight checks ---
    echo "=== Figure 4 Evaluation (lncot-exp4) ==="
    echo ""

    # Resolve full checkpoint path (may have nested subdirs from exp_name)
    if [ ! -d "$CHECKPOINT_DIR" ]; then
        echo "ERROR: Checkpoint directory not found: $CHECKPOINT_DIR"
        echo ""
        echo "  Available experiment dirs:"
        ls -1d /scratch/ab3u21/exps/owt2/adaptive_cotformer_*/ 2>/dev/null || echo "  (none found)"
        echo ""
        echo "  Set CHECKPOINT_DIR in this script to the correct path."
        exit 1
    fi

    # Find the actual experiment subdir (exp_name creates nested dirs)
    CKPT_FILE=$(find "$CHECKPOINT_DIR" -name "ckpt.pt" -type f 2>/dev/null | head -1)
    if [ -z "$CKPT_FILE" ]; then
        echo "ERROR: No ckpt.pt found under $CHECKPOINT_DIR"
        echo "  Training may not have completed yet."
        echo "  Resubmit: bash iridis/adm-train/job.sh"
        exit 1
    fi
    CKPT_SUBDIR=$(dirname "$CKPT_FILE")

    SUMMARY_FILE="$CKPT_SUBDIR/summary.json"
    if [ ! -f "$SUMMARY_FILE" ]; then
        echo "ERROR: No summary.json found at $CKPT_SUBDIR"
        echo "  Training completed but summary was not written."
        echo "  This usually means training was interrupted at the very end."
        exit 1
    fi

    echo "  Checkpoint: $CKPT_SUBDIR"
    echo "  ckpt.pt:    $(ls -lh "$CKPT_FILE" | awk '{print $5}')"
    echo "  summary:    OK"
    echo ""

    RUN_DIR=$(next_run_dir "$PACKAGE_DIR")
    echo "  Logs: $RUN_DIR/"
    echo ""
    exec sbatch \
        --output="$RUN_DIR/slurm_%j.out" \
        --error="$RUN_DIR/slurm_%j.err" \
        --mail-type=BEGIN,END,FAIL \
        --mail-user="$NOTIFY_EMAIL" \
        --export=ALL,REPO_DIR="$REPO_DIR",CHECKPOINT_DIR="$CHECKPOINT_DIR" \
        "$0" "$@"
fi

# --- Actual job (runs on compute node) ---
set -eo pipefail
export PYTHONUNBUFFERED=1

if [ -z "$REPO_DIR" ]; then
    REPO_DIR="$HOME/CoTFormer"
    echo "WARNING: REPO_DIR not set — falling back to $REPO_DIR"
fi

source "$REPO_DIR/iridis/env.sh"

mkdir -p "$DATA_DIR" "$HF_HOME" "$TIKTOKEN_CACHE_DIR"

echo "========================================="
echo " Figure 4 Evaluation (lncot-exp4)"
echo " User:       $USER"
echo " Node:       $(hostname)"
echo " Job ID:     $SLURM_JOB_ID"
echo " Checkpoint: $CHECKPOINT_DIR"
echo " Started:    $(date)"
echo "========================================="

# --- Environment ---
module load conda
eval "$(conda shell.bash hook)"
conda activate "$CONDA_ENV_PREFIX"

cd "$REPO_DIR"

# --- GPU info ---
echo ""
nvidia-smi --query-gpu=index,name,memory.total --format=csv,noheader
echo ""

# --- Verify dataset ---
if [ ! -f "$DATA_DIR/openwebtext2/train.bin" ]; then
    echo "ERROR: Dataset not found at $DATA_DIR/openwebtext2/train.bin"
    exit 1
fi

# --- Find checkpoint subdir (exp_name creates nested dirs) ---
CKPT_FILE=$(find "$CHECKPOINT_DIR" -name "ckpt.pt" -type f 2>/dev/null | head -1)
CKPT_SUBDIR=$(dirname "$CKPT_FILE")
echo "Resolved checkpoint subdir: $CKPT_SUBDIR"
echo ""

# ========================= PHASE 1: Extract Router Weights ==================
echo "========================================="
echo " Phase 1: Extracting router weights"
echo "========================================="

if [ -f "$CKPT_SUBDIR/router_weights.npy" ]; then
    echo "router_weights.npy already exists — skipping extraction."
    echo "  Delete it to force re-extraction."
else
    python get_router_weights.py --checkpoint "$CKPT_SUBDIR"
    echo ""
    echo "Router weights saved: $CKPT_SUBDIR/router_weights.npy"
fi

echo ""

# ========================= PHASE 2: Evaluate Per MAC Budget =================
echo "========================================="
echo " Phase 2: Evaluating perplexity vs MACs"
echo "   Thresholds: 0.0, 0.1, 0.2, 0.4, 0.6, 0.8, 0.85, 0.9, 0.95, 1.0"
echo "   Fixed depths: 1, 2, 3, 4 prefix repeats"
echo "========================================="

python get_ppl_per_mac.py --checkpoint "$CKPT_SUBDIR"

echo ""

# ========================= DONE =============================================
echo "========================================="
echo " Figure 4 evaluation complete: $(date)"
echo ""
echo " Output files:"
echo "   $CKPT_SUBDIR/router_weights.npy"
echo "   $CKPT_SUBDIR/eval_per_threshold.npy   (Router curve)"
echo "   $CKPT_SUBDIR/eval_per_layer.npy       (Fixed Depth curve)"
echo ""
echo " Next: use these .npy files with plot_adm_pareto.py (Phase 5)"
echo "========================================="

exit 0
